<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\Event\Event;

/**
 * News Controller
 *
 * @property \Admin\Model\Table\NewsTable $News
 */
class NewsController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->titleLayout = __('News');
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $news = $this->News->find('all', [
            'contain' => ['NewsCategories'],
            'order' => ['News.modified' => 'desc']
        ]);
        if ($news) {
            $news = $news->toArray();
        }
        $this->set('news', $news);
        $this->set('_serialize', ['news']);
    }

    /**
     * View method
     *
     * @param string|null $id News id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $news = $this->News->get($id, [
            'contain' => ['NewsCategories']
        ]);
        $this->set('news', $news);
        $this->set('_serialize', ['news']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $news = $this->News->newEntity();
        if ($this->request->is('post')) {
            $news = $this->Core->patchEntity($news, $this->request->data,'Admin.News');
            if ($this->News->save($news)) {
                $this->Flash->success(__('The news has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The news could not be saved. Please, try again.'));
            }
        }
        $this->loadModel('NewsCategories');
        $newsCategories = $this->NewsCategories->find('list', ['limit' => 200,'valueField'=>'name_'.$this->fieldLanguage]);
        $this->imageFields = $news->imageFields;
        $this->set(compact('news', 'newsCategories'));
        $this->set('_serialize', ['news']);
    }

    /**
     * Edit method
     *
     * @param string|null $id News id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $news = $this->News->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $news = $this->Core->patchEntity($news, $this->request->data,'Admin.News');
            if ($this->News->save($news)) {
                $this->Flash->success(__('The news has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The news could not be saved. Please, try again.'));
            }
        }
        $newsCategories = $this->News->NewsCategories->find('list', ['limit' => 200, 'valueField' => 'name_'.$this->fieldLanguage]);
        $this->imageFields = $news->imageFields;
        $this->set(compact('news', 'newsCategories'));
        $this->set('_serialize', ['news']);
    }

    /**
     * Delete method
     *
     * @param string|null $id News id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        if($this->allowAccess == false) return;
        $this->request->allowMethod(['post', 'delete']);
        $news = $this->News->get($id);
        if ($this->News->delete($news)) {
            $this->Flash->success(__('The news has been deleted.'));
        } else {
            $this->Flash->error(__('The news could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
