<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\Event\Event;

/**
 * TopListInquiries Controller
 *
 * @property \Admin\Model\Table\TopListInquiriesTable $TopListInquiries
 */
class TopListInquiriesController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->titleLayout = __('Top Inquiry');
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->set('topListInquiries', $this->TopListInquiries->find('all'));
        $this->set('_serialize', ['topListInquiries']);
    }

    /**
     * View method
     *
     * @param string|null $id Top List Inquiry id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $topListInquiry = $this->TopListInquiries->get($id, [
            'contain' => []
        ]);
        $this->set('topListInquiry', $topListInquiry);
        $this->set('_serialize', ['topListInquiry']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $topListInquiry = $this->TopListInquiries->newEntity();
        if ($this->request->is('post')) {
            $topListInquiry = $this->TopListInquiries->patchEntity($topListInquiry, $this->request->data);
            if ($this->TopListInquiries->save($topListInquiry)) {
                $this->Flash->success(__('The top list inquiry has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The top list inquiry could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('topListInquiry'));
        $this->set('_serialize', ['topListInquiry']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Top List Inquiry id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $topListInquiry = $this->TopListInquiries->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $topListInquiry = $this->TopListInquiries->patchEntity($topListInquiry, $this->request->data);
            if ($this->TopListInquiries->save($topListInquiry)) {
                $this->Flash->success(__('The top list inquiry has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The top list inquiry could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('topListInquiry'));
        $this->set('_serialize', ['topListInquiry']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Top List Inquiry id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        if($this->allowAccess == false) return;
        $this->request->allowMethod(['post', 'delete']);
        $topListInquiry = $this->TopListInquiries->get($id);
        if ($this->TopListInquiries->delete($topListInquiry)) {
            $this->Flash->success(__('The top list inquiry has been deleted.'));
        } else {
            $this->Flash->error(__('The top list inquiry could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
