<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\Event\Event;

/**
 * TypeCompanies Controller
 *
 * @property \Admin\Model\Table\TypeCompaniesTable $TypeCompanies
 */
class TypeCompaniesController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->titleLayout = __('Classification of company');
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->paginate = [
            'order' => ['order' => 'ASC']
        ];
        $this->set('typeCompanies', $this->TypeCompanies->find('all'));
        $this->set('_serialize', ['typeCompanies']);
    }

    /**
     * View method
     *
     * @param string|null $id Type Company id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $typeCompany = $this->TypeCompanies->get($id, [
            'contain' => []
        ]);
        $this->set('typeCompany', $typeCompany);
        $this->set('_serialize', ['typeCompany']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $typeCompany = $this->TypeCompanies->newEntity();
        if ($this->request->is('post')) {
            $typeCompany = $this->TypeCompanies->patchEntity($typeCompany, $this->request->data);
            if ($this->TypeCompanies->save($typeCompany)) {
                $this->Flash->success(__('The type company has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The type company could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('typeCompany'));
        $this->set('_serialize', ['typeCompany']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Type Company id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $typeCompany = $this->TypeCompanies->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $typeCompany = $this->TypeCompanies->patchEntity($typeCompany, $this->request->data);
            if ($this->TypeCompanies->save($typeCompany)) {
                $this->Flash->success(__('The type company has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The type company could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('typeCompany'));
        $this->set('_serialize', ['typeCompany']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Type Company id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        if($this->allowAccess == false) return;
        $this->request->allowMethod(['post', 'delete']);
        $typeCompany = $this->TypeCompanies->get($id);
        if ($this->TypeCompanies->delete($typeCompany)) {
            $this->Flash->success(__('The type company has been deleted.'));
        } else {
            $this->Flash->error(__('The type company could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
