<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\Event\Event;

/**
 * TypeBusiness Controller
 *
 * @property \Admin\Model\Table\TypeBusinessTable $TypeBusiness
 */
class TypeBusinessController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->titleLayout = __('Type Business');
    }
    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->set('typeBusiness',$this->TypeBusiness->find('all'));
        $this->set('_serialize', ['typeBusiness']);
    }

    /**
     * View method
     *
     * @param string|null $id Type Busines id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $typeBusines = $this->TypeBusiness->get($id, [
            'contain' => []
        ]);
        $this->set('typeBusines', $typeBusines);
        $this->set('_serialize', ['typeBusines']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $typeBusines = $this->TypeBusiness->newEntity();
        if ($this->request->is('post')) {
            $typeBusines = $this->TypeBusiness->patchEntity($typeBusines, $this->request->data);
            if ($this->TypeBusiness->save($typeBusines)) {
                $this->Flash->success(__('The type busines has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The type busines could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('typeBusines'));
        $this->set('_serialize', ['typeBusines']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Type Busines id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $typeBusines = $this->TypeBusiness->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $typeBusines = $this->TypeBusiness->patchEntity($typeBusines, $this->request->data);
            if ($this->TypeBusiness->save($typeBusines)) {
                $this->Flash->success(__('The type busines has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The type busines could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('typeBusines'));
        $this->set('_serialize', ['typeBusines']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Type Busines id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        if($this->allowAccess == false) return;
        $this->request->allowMethod(['post', 'delete']);
        $typeBusines = $this->TypeBusiness->get($id);
        if ($this->TypeBusiness->delete($typeBusines)) {
            $this->Flash->success(__('The type busines has been deleted.'));
        } else {
            $this->Flash->error(__('The type busines could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
